# Generated by Django 5.0.1 on 2024-01-17 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_friends_friendshiprequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendShipRequest',
            new_name='FriendShipRequests',
        ),
    ]
