# Generated by Django 5.0.1 on 2024-01-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_friendshiprequest_friendshiprequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='friendshiprequests',
            name='status',
            field=models.CharField(choices=[('sent', 'Send'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='sent', max_length=20),
        ),
    ]
