# Generated by Django 5.0 on 2024-05-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_people_you_may_know_friendshiprequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendshiprequest',
            name='request_sent',
            field=models.BooleanField(default=False),
        ),
    ]
