# Generated by Django 5.0.1 on 2024-01-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_comments_count_comment_post_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',)},
        ),
    ]
