# Generated by Django 5.0.1 on 2024-01-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_trend'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trend',
            new_name='Trends',
        ),
    ]
