# Generated by Django 5.0 on 2024-05-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_user_conversation_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
